services:
  server:
    container_name: nest-api-books
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: "books-db"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432